---
http_interactions:
- request:
    method: post
    uri: http://soap.valleymetro.org/cgi-bin-soap-web-271/soap.cgi
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsdl="PX_WEB"
        xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><Point2point
        xmlns="PX_WEB"><Routesonly>N</Routesonly><Originlat>33.446931</Originlat><Originlong>-112.097903</Originlong><Destinationlat>33.447098</Destinationlat><Destinationlong>-112.077213</Destinationlong><Date>06/13/2014</Date><Starttime>1700</Starttime><Endtime>1800</Endtime><Routes>1,I10E</Routes><Appid>ratis-specs</Appid></Point2point></env:Body></env:Envelope>
    headers:
      Soapaction:
      - '"PX_WEB#Point2point"'
      Content-Type:
      - text/xml;charset=UTF-8
      Content-Length:
      - '607'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - '*/*'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Sat, 14 Jun 2014 00:42:27 GMT
      Server:
      - Apache/2.2.3 (CentOS)
      Soapserver:
      - SOAP::Lite/Perl/0.55
      Content-Length:
      - '4310'
      Connection:
      - close
      Content-Type:
      - text/xml; charset=utf-8
    body:
      encoding: UTF-8
      string: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><SOAP-ENV:Envelope xmlns:xsi=\"http://www.w3.org/1999/XMLSchema-instance\"
        xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\"
        xmlns:xsd=\"http://www.w3.org/1999/XMLSchema\" SOAP-ENV:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><SOAP-ENV:Body><namesp1:Point2pointResponse
        xmlns:namesp1=\"PX_WEB\">\n\t<Responsecode>0</Responsecode>\n\t<Version>1.7</Version>\n\t<Groups>\n\t\t<Group>\n\t\t\t<Onstop>\n\t\t\t\t<Description>JEFFERSON
        ST &amp; 18TH AVE</Description>\t\t\t\t<Area>Phoenix</Area>\n\t\t\t\t<Lat>33.446900</Lat>\n\t\t\t\t<Long>-112.097897</Long>\n\t\t\t\t<Atisstopid>9469</Atisstopid>\n\t\t\t\t<Stopid>16855</Stopid>\n\t\t\t\t<Onwalkdist>0.0</Onwalkdist>\n\t\t\t\t<Onwalkdir>S</Onwalkdir>\n\t\t\t\t<Onwalkhint>N</Onwalkhint>\n\t\t\t\t<Stopstatustype>N</Stopstatustype>\n\t\t\t</Onstop>\n\t\t\t<Offstop>\n\t\t\t\t<Description>JEFFERSON
        ST &amp;amp; 18TH AVE</Description>\t\t\t\t<Area>Phoenix</Area>\n\t\t\t\t<Lat>33.447029</Lat>\n\t\t\t\t<Long>-112.077181</Long>\n\t\t\t\t<Atisstopid>1463</Atisstopid>\n\t\t\t\t<Offstopwalk>0.0</Offstopwalk>\n\t\t\t\t<Offstopwalkdir>SE</Offstopwalkdir>\n\t\t\t\t<Offstopwalkhint>N</Offstopwalkhint>\n\t\t\t\t<Stopstatustype>N</Stopstatustype>\n\t\t\t</Offstop>\n\t\t\t<Trips>\n\t\t\t\t<Trip>\n\t\t\t\t\t<Ontime>05:01
        PM</Ontime>\n\t\t\t\t\t<Offtime>05:08 PM</Offtime>\n\t\t\t\t\t<Service>\n\t\t\t\t\t\t<Route>I10E</Route>\n\t\t\t\t\t\t<Publicroute></Publicroute>\n\t\t\t\t\t\t<Direction>O</Direction>\n\t\t\t\t\t\t<Servicetype>W</Servicetype>\n\t\t\t\t\t\t<Signage>I-10
        EAST RAPID To 40 St/Pecos</Signage>\n\t\t\t\t\t\t<Routetype>N</Routetype>\n\t\t\t\t\t\t<Statustype></Statustype>\n\t\t\t\t\t\t<Exception>N</Exception>\n\t\t\t\t\t</Service>\n\t\t\t\t</Trip>\n\t\t\t\t<Trip>\n\t\t\t\t\t<Ontime>05:21
        PM</Ontime>\n\t\t\t\t\t<Offtime>05:28 PM</Offtime>\n\t\t\t\t\t<Service>\n\t\t\t\t\t\t<Route>I10E</Route>\n\t\t\t\t\t\t<Publicroute></Publicroute>\n\t\t\t\t\t\t<Direction>O</Direction>\n\t\t\t\t\t\t<Servicetype>W</Servicetype>\n\t\t\t\t\t\t<Signage>I-10
        EAST RAPID To 40 St/Pecos</Signage>\n\t\t\t\t\t\t<Routetype>N</Routetype>\n\t\t\t\t\t\t<Statustype></Statustype>\n\t\t\t\t\t\t<Exception>N</Exception>\n\t\t\t\t\t</Service>\n\t\t\t\t</Trip>\n\t\t\t\t<Trip>\n\t\t\t\t\t<Ontime>05:41
        PM</Ontime>\n\t\t\t\t\t<Offtime>05:48 PM</Offtime>\n\t\t\t\t\t<Service>\n\t\t\t\t\t\t<Route>I10E</Route>\n\t\t\t\t\t\t<Publicroute></Publicroute>\n\t\t\t\t\t\t<Direction>O</Direction>\n\t\t\t\t\t\t<Servicetype>W</Servicetype>\n\t\t\t\t\t\t<Signage>I-10
        EAST RAPID To 40 St/Pecos</Signage>\n\t\t\t\t\t\t<Routetype>N</Routetype>\n\t\t\t\t\t\t<Statustype></Statustype>\n\t\t\t\t\t\t<Exception>N</Exception>\n\t\t\t\t\t</Service>\n\t\t\t\t</Trip>\n\t\t\t</Trips>\n\t\t</Group>\n\t\t<Group>\n\t\t\t<Onstop>\n\t\t\t\t<Description>EB
        JEFFERSON ST NS 17TH AVE</Description>\t\t\t\t<Area>Phoenix</Area>\n\t\t\t\t<Lat>33.446985</Lat>\n\t\t\t\t<Long>-112.096808</Long>\n\t\t\t\t<Atisstopid>1469</Atisstopid>\n\t\t\t\t<Stopid>10202</Stopid>\n\t\t\t\t<Onwalkdist>0.1</Onwalkdist>\n\t\t\t\t<Onwalkdir>E</Onwalkdir>\n\t\t\t\t<Onwalkhint>N</Onwalkhint>\n\t\t\t\t<Stopstatustype>N</Stopstatustype>\n\t\t\t</Onstop>\n\t\t\t<Offstop>\n\t\t\t\t<Description>EB
        JEFFERSON ST NS 17TH AVE</Description>\t\t\t\t<Area>Phoenix</Area>\n\t\t\t\t<Lat>33.447029</Lat>\n\t\t\t\t<Long>-112.077181</Long>\n\t\t\t\t<Atisstopid>1463</Atisstopid>\n\t\t\t\t<Offstopwalk>0.0</Offstopwalk>\n\t\t\t\t<Offstopwalkdir>SE</Offstopwalkdir>\n\t\t\t\t<Offstopwalkhint>N</Offstopwalkhint>\n\t\t\t\t<Stopstatustype>N</Stopstatustype>\n\t\t\t</Offstop>\n\t\t\t<Trips>\n\t\t\t\t<Trip>\n\t\t\t\t\t<Ontime>05:10
        PM</Ontime>\n\t\t\t\t\t<Offtime>05:16 PM</Offtime>\n\t\t\t\t\t<Service>\n\t\t\t\t\t\t<Route>1</Route>\n\t\t\t\t\t\t<Publicroute></Publicroute>\n\t\t\t\t\t\t<Direction>E</Direction>\n\t\t\t\t\t\t<Servicetype>W</Servicetype>\n\t\t\t\t\t\t<Signage>1
        Washington to Sky Train/Sky Harbor</Signage>\n\t\t\t\t\t\t<Routetype>D</Routetype>\n\t\t\t\t\t\t<Statustype></Statustype>\n\t\t\t\t\t\t<Exception>N</Exception>\n\t\t\t\t\t</Service>\n\t\t\t\t</Trip>\n\t\t\t\t<Trip>\n\t\t\t\t\t<Ontime>05:55
        PM</Ontime>\n\t\t\t\t\t<Offtime>06:01 PM</Offtime>\n\t\t\t\t\t<Service>\n\t\t\t\t\t\t<Route>1</Route>\n\t\t\t\t\t\t<Publicroute></Publicroute>\n\t\t\t\t\t\t<Direction>E</Direction>\n\t\t\t\t\t\t<Servicetype>W</Servicetype>\n\t\t\t\t\t\t<Signage>1
        Washington to Sky Train/Sky Harbor</Signage>\n\t\t\t\t\t\t<Routetype>D</Routetype>\n\t\t\t\t\t\t<Statustype></Statustype>\n\t\t\t\t\t\t<Exception>N</Exception>\n\t\t\t\t\t</Service>\n\t\t\t\t</Trip>\n\t\t\t</Trips>\n\t\t</Group>\n\t</Groups>\n\t<Appid>ratis-specs</Appid>\n\t<Requestor>72.222.151.25</Requestor>\n\t<Host>s-rpta-soap</Host>\n\t<Copyright>XML
        schema Copyright (c) 2003-2014 Trapeze Software ULC, its subsidiaries and
        affiliates.  All rights reserved.</Copyright>\n\t<Soapversion>2.7.1a - 05/14/14</Soapversion>\n</namesp1:Point2pointResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>"
    http_version: 
  recorded_at: Sat, 14 Jun 2014 00:42:27 GMT
recorded_with: VCR 2.8.0
