require 'ratis/atis_itinerary'
require 'ratis/atis_landmark'
require 'ratis/atis_landmark_category'
require 'ratis/atis_location'
require 'ratis/atis_model'
require 'ratis/atis_next_bus'
require 'ratis/atis_route'
require 'ratis/atis_schedule_nearby'
require 'ratis/atis_stop'
require 'ratis/atis_timetable'
require 'ratis/atis_walk'

