---
http_interactions:
- request:
    method: post
    uri: http://soap.valleymetro.org/cgi-bin-soap-web-271/soap.cgi
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsdl="PX_WEB"
        xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><Point2point
        xmlns="PX_WEB"><Routesonly>Y</Routesonly><Originlat>33.446931</Originlat><Originlong>-112.097903</Originlong><Destinationlat>33.447098</Destinationlat><Destinationlong>-112.077213</Destinationlong><Date>06/16/2014</Date><Starttime>1700</Starttime><Endtime>1800</Endtime><Routes>1</Routes><Appid>ratis-specs</Appid></Point2point></env:Body></env:Envelope>
    headers:
      Soapaction:
      - '"PX_WEB#Point2point"'
      Content-Type:
      - text/xml;charset=UTF-8
      Content-Length:
      - '602'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - '*/*'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Sat, 14 Jun 2014 00:42:21 GMT
      Server:
      - Apache/2.2.3 (CentOS)
      Soapserver:
      - SOAP::Lite/Perl/0.55
      Content-Length:
      - '5971'
      Connection:
      - close
      Content-Type:
      - text/xml; charset=utf-8
    body:
      encoding: UTF-8
      string: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><SOAP-ENV:Envelope xmlns:xsi=\"http://www.w3.org/1999/XMLSchema-instance\"
        xmlns:SOAP-ENC=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\"
        xmlns:xsd=\"http://www.w3.org/1999/XMLSchema\" SOAP-ENV:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><SOAP-ENV:Body><namesp1:Point2pointResponse
        xmlns:namesp1=\"PX_WEB\">\t<Version>1.7</Version>\n\n\t<Responsecode>0</Responsecode>\n\t<Version>1.7</Version>\n\t<Routes>\n\t\t<Service>\n\t\t\t<Route>562</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>562
        Goodyear To Goodyear</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>D</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>I10E</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>I-10
        EAST RAPID To 40 St/Pecos</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>CSM</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>CSM
        RAPID To 27th Av/Bsln PNR</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>3</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>E</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>3
        VAN BUREN East to Phoenix Zoo</Signage>\n\t\t\t<Routetype>B</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>I10W</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>I-10
        WEST RAPID to Desert Sky Mall Via 79Ave/I-10</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>541</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>541
        Chandler To Arizona/Ray Via West Mesa PNR</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>533</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>533
        Mesa To Suprstn Sprg PNR</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>522</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>522
        Tempe To Warner/CC Way</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>521</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>521
        Tempe To Price/Baseline</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>520</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>520
        Tempe To Price/Bdwy</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>514</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>514
        Scottsdale To Fountn Hills</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>1</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>E</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>1
        Washington to Sky Train/Sky Harbor</Signage>\n\t\t\t<Routetype>B</Routetype>\n\t\t\t\t\t\t<Statustype>D</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>DASG</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>K</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>DASH
        Gvrnmnt To State Capitl</Signage>\n\t\t\t<Routetype>B</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>542</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>542
        Chandler To Chandler PNR</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>531</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>531
        Mesa/Gilbrt To Dntn Gilbert Via West Mesa PNR</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>563</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>563
        Buckeye To Buckeye P&amp;R Via Goodyear P&amp;R</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>A</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>535</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>535
        Mesa To Power Rd PNR Via Gilb/McDwl PNR</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>571</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>571
        Surprise To Surprise PNR</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>N</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>SR51</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>SR-51
        RAPID To Bell/SR-51 Via Shea/SR-51</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>D</Statustype>\n\t\t</Service>\n\t\t<Service>\n\t\t\t<Route>573</Route>\n\t\t\t<Publicroute></Publicroute>\n\t\t\t<Direction>O</Direction>\n\t\t\t<Servicetype>W</Servicetype>\n\t\t\t<Signage>573
        N Glendale 59/Beardsley Via I-10</Signage>\n\t\t\t<Routetype>X</Routetype>\n\t\t\t\t\t\t<Statustype>D</Statustype>\n\t\t</Service>\n\t</Routes>\n\t<Appid>ratis-specs</Appid>\n\t<Requestor>72.222.151.25</Requestor>\n\t<Host>s-rpta-soap</Host>\n\t<Copyright>XML
        schema Copyright (c) 2003-2014 Trapeze Software ULC, its subsidiaries and
        affiliates.  All rights reserved.</Copyright>\n\t<Soapversion>2.7.1a - 05/14/14</Soapversion>\n</namesp1:Point2pointResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>"
    http_version: 
  recorded_at: Sat, 14 Jun 2014 00:42:21 GMT
recorded_with: VCR 2.8.0
